//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanfactREST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PlanfactEntities : DbContext
    {
        public PlanfactEntities()
            : base("name=PlanfactEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
    
        public virtual ObjectResult<AvgSumPerHour_Result> AvgSumPerHour(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AvgSumPerHour_Result>("AvgSumPerHour", statusParameter);
        }
    
        public virtual ObjectResult<BirthdateSum_Result> BirthdateSum(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BirthdateSum_Result>("BirthdateSum", statusParameter);
        }

        public System.Data.Entity.DbSet<PlanfactREST.Models.BirthdateSum_Result> BirthdateSum_Result { get; set; }

        public System.Data.Entity.DbSet<PlanfactREST.Models.AvgSumPerHour_Result> AvgSumPerHour_Result { get; set; }
    }
}
